# Generated by Django 4.1.4 on 2022-12-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
    ]
