# Generated by Django 4.1.4 on 2022-12-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='active',
        ),
    ]
