# Generated by Django 4.1.1 on 2022-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='listed_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
