# Generated by Django 4.1.4 on 2022-12-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='listed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidded_item',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid',
                                    to='auctions.auctionitem'),
        ),
    ]
