# Generated by Django 4.1.4 on 2022-12-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auctionitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
