# Generated by Django 4.1.4 on 2022-12-22 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionitem')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
