# Generated by Django 4.1.1 on 2022-09-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
