# Generated by Django 4.1.4 on 2022-12-19 08:31

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionitem_image_url_auctionitem_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=1, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=1, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
