# Generated by Django 4.1.1 on 2022-09-23 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
