# Generated by Django 4.1.4 on 2022-12-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionitem_watchlist_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
