# Generated by Django 4.1.1 on 2022-09-26 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionbid_auction_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbid',
            name='auction_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionitem'),
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
