# Generated by Django 4.1.1 on 2022-09-23 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionitem_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
