# Generated by Django 4.1.4 on 2022-12-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionitem_image_link'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_item_watchlist'),
        ),
    ]
