# Generated by Django 4.1.1 on 2022-09-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='auction_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionitem'),
        ),
    ]
