# Generated by Django 4.1.4 on 2022-12-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0006_remove_watchlist_unique_user_item_watchlist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_item_watchlist'),
        ),
    ]
