# Generated by Django 4.1.4 on 2022-12-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0007_watchlist_unique_user_item_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionbid',
            options={'ordering': ['-created'], 'verbose_name': 'Auction Bid', 'verbose_name_plural': 'Auction Bids'},
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids',
                                    to='auctions.auctionitem'),
        ),
    ]
