# Generated by Django 4.1.4 on 2022-12-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionbid_options_alter_auctionitem_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('owner', 'item'), name='unique_user_item_comment'),
        ),
    ]
