# Generated by Django 4.1.4 on 2023-01-03 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0014_alter_auctionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
